### ISSUE TITLE
ADD failed: file not found in build context or excluded by .dockerignore: stat target/cms.war: file does not exist

### ISSUE THREAD

**Issue by secnotes** [mukeshpilaniya/cms#1]
This error occurred in building spring boot on multiple Linux distributions:

```shell
test@test-ubuntu:~/Tools/cms$ sudo docker build -t cms-springboot .
Sending build context to Docker daemon  3.584kB
Step 1/8 : FROM openjdk:8
 ---> fec1c6e1f497
Step 2/8 : LABEL maintainer="iiitb"
 ---> Using cache
 ---> 5cd67b5a4144
Step 3/8 : VOLUME /tmp
 ---> Using cache
 ---> 45ad623662b6
Step 4/8 : EXPOSE 8082
 ---> Using cache
 ---> d4891c795e93
Step 5/8 : ADD /target/cms.war cms.war
ADD failed: file not found in build context or excluded by .dockerignore: stat target/cms.war: file does not exist
```

**Comment by mukeshpilaniya** [comment]
@liyansong2018  this is not an issue for this first you have to build a cms.war file. To build cms.war navigate to the project directory where you have cloned this project and then type
`maven clean package` and then it will generate a target folder, inside it there is a cms.war file after that you can able to run
`sudo docker build -t cms-springboot .`

**Comment by mukeshpilaniya** [comment]
To run this project directly without hassle you can try these commands
`docker pull pilaniya1337/cms` 
`docker run -t -p 8082:8082 --name cms-springboot --link cms-mysql:mysql -d pilaniya1337/cms`

then
```
Go to:- http://loaclhost:8082
username- admin
password- admin
```

**Comment by secnotes** [comment]
Thanks.
